apiVersion: deployments.plural.sh/v1alpha1
kind: Pipeline
metadata:
  name: podinfo
spec:
  stages:
    - name: dev
      services:
        - serviceRef:
            name: podinfo
            namespace: dev
          criteria:
            prAutomationRef:
              name: podinfo-pipeline
    - name: prod
      services:
        - serviceRef:
            name: podinfo
            namespace: prod
          criteria:
            prAutomationRef:
              name: podinfo-pipeline
  edges:
    - from: dev
      to: prod
      gates:
      - name: approval-gate
        type: APPROVAL