apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: podinfo-pipeline-automation
spec:
  name: podinfo-pipeline-automation
  documentation: Updates the podinfo service to a specified helm version for any pipeline stage
  updates:
    regexReplacements:
    - regex: "tag: (.*) # VERSION"
      file: "{{ context.pipeline.stage.name }}/podinfo.yaml"
      replacement: "tag: {{ context.version }} # VERSION"
  scmConnectionRef:
    name: gh-test
  title: "Updating pod info prod helm version to {{ context.version }} (stage={{ context.pipeline.stage.name }})"
  message: "Updating pod info prod helm version to {{ context.version }} (stage={{ context.pipeline.stage.name }})"
  identifier: pluralsh/pipelines-demo
  configuration:
  - name: version
    type: STRING
    documentation: The helm chart version to use