apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: dev
spec:
  name: pipeline-dev
  namespace: prodinfo-pipeline
  git:
    folder: dev
    ref: main
  repositoryRef:
    kind: GitRepository
    name: demo
    namespace: infra
  clusterRef:
    kind: Cluster
    name: mgmt # change this to the appropriate name for your main test cluster
    namespace: infra