apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: podinfo-pipeline
spec:
  name: podinfo-pipeline
  namespace: podinfo-pipeline
  templated: false
  git:
    folder: pipeline
    ref: main
  repositoryRef:
    kind: GitRepository
    name: demo
    namespace: infra
  clusterRef:
    kind: Cluster
    name: mgmt # change this to the appropriate name for your main test cluster
    namespace: infra