apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: pipeline-podinfo-prod
  namespace: prod
spec:
  serviceRef:
    name: podinfo
    namespace: prod
  tags:
    tier: prod
